spring.application.name=tenant-service

spring.datasource.url=jdbc:postgresql://localhost:5432/tenant_db
spring.datasource.username=aguser
spring.datasource.password=agpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=8081

app.jwt.secret=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7e4b52d7b4c0430a60bc3ee94b
app.jwt.access-token-expiry-ms=900000
app.jwt.refresh-token-expiry-ms=604800000
logging.level.org.springframework.security=DEBUG